"""add message status/tokens/cost, expand usage_counters

Revision ID: 4c3448fe4bfe
Revises: 312edb87a088
Create Date: 2026-09-14 17:13:29.342042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c3448fe4bfe'
down_revision: Union[str, Sequence[str], None] = '312edb87a088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows so the NOT NULL constraint doesn't
    # fail on a non-empty table. "completed" matches MessageStatus.COMPLETED and
    # is the right assumption for rows that predate this migration — they were
    # already fully processed under the old echo-stub/OpenRouter code path.
    op.add_column('messages', sa.Column('status', sa.String(), nullable=False, server_default='completed'))
    op.add_column('messages', sa.Column('prompt_tokens', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('messages', sa.Column('completion_tokens', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('messages', sa.Column('est_cost', sa.Float(), nullable=True, server_default='0'))
    op.add_column('usage_counters', sa.Column('messages_today', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('usage_counters', sa.Column('tokens_today', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('usage_counters', sa.Column('est_spend_today', sa.Float(), nullable=True, server_default='0'))
    op.drop_column('usage_counters', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_counters', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('usage_counters', 'est_spend_today')
    op.drop_column('usage_counters', 'tokens_today')
    op.drop_column('usage_counters', 'messages_today')
    op.drop_column('messages', 'est_cost')
    op.drop_column('messages', 'completion_tokens')
    op.drop_column('messages', 'prompt_tokens')
    op.drop_column('messages', 'status')
    # ### end Alembic commands ###